// Instituciones financieras de Ecuador (para el campo "Banco" de las transferencias).
// Los primeros son los más usados; luego el resto y las cooperativas grandes.
export const BANCOS_EC = [
  'Banco Pichincha',
  'Banco Guayaquil',
  'Banco del Pacífico',
  'Produbanco',
  'Banco Bolivariano',
  'Banco Internacional',
  'Banco del Austro',
  'Banco Solidario',
  'Banco de Loja',
  'Banco de Machala',
  'Banco ProCredit',
  'Banco Amazonas',
  'Banco General Rumiñahui',
  'Banco Comercial de Manabí',
  'Banco del Litoral',
  'Banco Capital',
  'Banco Coopnacional',
  'Banco D-MIRO',
  'Banco Delbank',
  'Banco Diners Club',
  'Bancodesarrollo',
  'BanEcuador',
  'BIESS',
  'Mutualista Pichincha',
  'Mutualista Azuay',
  'Mutualista Imbabura',
  'Mutualista Ambato',
  'Cooperativa JEP',
  'Cooperativa Jardín Azuayo',
  'Cooperativa Policía Nacional',
  'Cooperativa 29 de Octubre',
  'Cooperativa Cooprogreso',
  'Cooperativa Alianza del Valle',
  'Cooperativa Andalucía',
  'Cooperativa San Francisco',
  'Cooperativa Riobamba',
  'Cooperativa OSCUS',
  'Cooperativa El Sagrario',
  'Cooperativa CACPECO',
  'Cooperativa Coopmego',
  'Cooperativa Atuntaqui',
  'Cooperativa Tulcán',
  'Cooperativa Pablo Muñoz Vega',
];
